; 基于 final.yaml 生成的 Clash Mini / subconverter 外部配置
; 1、规则集
ruleset=DIRECT,[]DOMAIN-SUFFIX,cos-pro-pri.xbstatic.com
; ruleset=DIRECT,[]DOMAIN-SUFFIX,synology.me
ruleset=🧪 Test,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🚫 Block,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Block.list
ruleset=💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=✨ AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=✨ AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
ruleset=✨ AI,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Copilot.list
ruleset=✨ AI,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Gemini.list
ruleset=✨ AI,clash-domain:https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/groq.list
ruleset=✨ AI,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Grok.list
ruleset=🤖 Meta AI,clash-classic:https://raw.githubusercontent.com/dollei-jay/fenliu/refs/heads/main/MetaAi.list
ruleset=🧠 Perplexity,clash-domain:https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/perplexity.list
ruleset=💼 Microsoft,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍎 Apple,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=🍎 Apple,clash-domain:https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.list
ruleset=🍎 Apple,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Apple.list
ruleset=💰 Crypto,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OKX/OKX.list
ruleset=💰 Crypto,clash-domain:https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bybit.list
ruleset=💰 Crypto,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🎥 流媒体,clash-ipcidr:https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Crunchyroll.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Popcorn.list
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🌐 Google,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PlayStation/PlayStation.list
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🟩 Nvidia,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nvidia/Nvidia.list
ruleset=💬 Reddit,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Reddit/Reddit.list
ruleset=🌍 国外,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🌍 国外,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,clash-classic:https://raw.githubusercontent.com/dollei-jay/fenliu/refs/heads/main/Direct.list
ruleset=➡️ 国内,clash-classic:https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Direct.list
ruleset=➡️ 国内,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=➡️ 国内,clash-domain:https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.list
ruleset=➡️ 国内,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=➡️ 国内,[]GEOIP,CN,no-resolve
ruleset=🧭 其他,[]FINAL

; 2、策略组（分流组）
; 全节点手动选择组
custom_proxy_group=🎯 手动切换`select`.*`[]DIRECT`[]REJECT

; 各分流策略组（加入手动选择组及各节点）
custom_proxy_group=✨ AI`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🤖 Meta AI`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🌐 Google`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🧠 Perplexity`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🎥 流媒体`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=💻 GitHub`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=💬 Reddit`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🟩 Nvidia`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🍎 Apple`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=💼 Microsoft`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🎮 Games`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=💰 Crypto`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🧪 Test`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=🚫 Block`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=🌍 国外`select`🎯 手动切换`.*`[]DIRECT`[]REJECT
custom_proxy_group=➡️ 国内`select`[]DIRECT`🎯 手动切换`.*`[]REJECT
custom_proxy_group=🧭 其他`select`🎯 手动切换`.*`[]DIRECT`[]REJECT

; 3、启用规则集
enable_rule_generator=true
